In [40]:
import pandas as pd
import numpy  as np
import tensorflow as tf
import matplotlib.pyplot as plt
from IPython.core.interactiveshell import InteractiveShell as IS
IS.ast_node_interactivity = "all"

In [41]:
import pandas as pd
churn = pd.read_csv('data/Churn_Modelling.csv')

In [42]:
df = churn.copy()
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [43]:
X = df.iloc[:, 3:13]
Y = df.iloc[:, 13]
X, Y

(      CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
 0             619    France  Female  ...          1               1        101348.88
 1             608     Spain  Female  ...          0               1        112542.58
 2             502    France  Female  ...          1               0        113931.57
 3             699    France  Female  ...          0               0         93826.63
 4             850     Spain  Female  ...          1               1         79084.10
 ...           ...       ...     ...  ...        ...             ...              ...
 9995          771    France    Male  ...          1               0         96270.64
 9996          516    France    Male  ...          1               1        101699.77
 9997          709    France  Female  ...          0               1         42085.58
 9998          772   Germany    Male  ...          1               0         92888.52
 9999          792    France  Female  ...          1  

In [44]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['Geography'] = le.fit_transform(X['Geography'])
X['Gender']    = le.fit_transform(X['Gender'])

In [45]:
X.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
dtype: int64

In [46]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose       import ColumnTransformer
ohe = ColumnTransformer([("ohe", OneHotEncoder(dtype=float), [1])], remainder="passthrough")

X = ohe.fit_transform(X)
X = X[:, 1:]

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing   import StandardScaler

In [48]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=0)
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test  = sc.fit_transform(x_test)

In [49]:
X_train, X_test

(array([[-0.56953701, -0.57436296, -1.78451879, ..., -1.56299709,
         -1.03339307,  1.0890591 ],
        [-0.56953701, -0.57436296,  1.47401668, ...,  0.63979645,
          0.967686  , -0.4551902 ],
        [-0.56953701, -0.57436296, -0.82854466, ..., -1.56299709,
          0.967686  , -0.65446947],
        ...,
        [-0.56953701, -0.57436296,  0.89837634, ...,  0.63979645,
         -1.03339307,  1.40745917],
        [-0.56953701,  1.74105933, -0.62295883, ...,  0.63979645,
          0.967686  ,  0.83939459],
        [ 1.75581215, -0.57436296, -0.2837422 , ...,  0.63979645,
         -1.03339307,  0.31973777]]),
 array([[ 1.67387076, -0.57268474, -0.55982398, ...,  0.65890748,
          0.97545271,  1.62753708],
        [-0.59741769, -0.57268474, -1.33593594, ...,  0.65890748,
         -1.02516503,  0.51106949],
        [-0.59741769,  1.74616143,  0.58336795, ...,  0.65890748,
          0.97545271, -0.4108104 ],
        ...,
        [-0.59741769,  1.74616143,  0.35263197, ..., -

In [77]:
import tensorflow as tf
tf.compat.v1.disable_v2_behavior()

hello = tf.constant('Hello, TensorFlow!')
sess = tf.compat.v1.Session()
print(sess.run(hello).decode())


Hello, TensorFlow!


In [51]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [67]:
classifier = Sequential() 
# Başlamgıc katmanı ilk olarak eklenmeli
classifier.add(Dense(6, kernel_initializer="uniform", activation ="relu", input_dim = 11)) # input layer
classifier.add(Dense(6, kernel_initializer="uniform", activation ="relu"))
classifier.add(Dense(1, kernel_initializer="uniform", activation ="sigmoid")) # Output layer
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
classifier.fit(X_train, y_train, epochs=50)

Epoch 1/50
210/210 [==============================] - 1s 828us/step - loss: 0.6181 - accuracy: 0.7967
Epoch 2/50
210/210 [==============================] - 1s 3ms/step - loss: 0.4450 - accuracy: 0.7979
Epoch 3/50
210/210 [==============================] - 1s 3ms/step - loss: 0.4317 - accuracy: 0.7979
Epoch 4/50
210/210 [==============================] - 1s 3ms/step - loss: 0.4290 - accuracy: 0.7979
Epoch 5/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4277 - accuracy: 0.7979
Epoch 6/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4265 - accuracy: 0.7979
Epoch 7/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4255 - accuracy: 0.7979
Epoch 8/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4245 - accuracy: 0.7979
Epoch 9/50
210/210 [==============================] - 1s 3ms/step - loss: 0.4233 - accuracy: 0.7979
Epoch 10/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4221 - accuracy: 0.79

In [68]:
y_pred = classifier.predict(X_test)

104/104 [==============================] - 0s 2ms/step


In [69]:
y_pred = (y_pred > 0.5).astype(int)

In [70]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm.

array([[2533,   84],
       [ 452,  231]])

In [81]:
# %cd data
# %ls
!wget install https://bilkav.com/Wine.csv

--2023-10-27 11:40:02--  http://install/
Resolving install (install)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘install’
--2023-10-27 11:40:02--  https://bilkav.com/Wine.csv
Resolving bilkav.com (bilkav.com)... 191.101.228.254
Connecting to bilkav.com (bilkav.com)|191.101.228.254|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘Wine.csv’

Wine.csv                [ <=>                ]  11.20K  --.-KB/s    in 0.04s   

2023-10-27 11:40:07 (286 KB/s) - ‘Wine.csv’ saved [11464]

FINISHED --2023-10-27 11:40:07--
Total wall clock time: 4.6s
Downloaded: 1 files, 11K in 0.04s (286 KB/s)


In [91]:
!wget https://bilkav.com/Wine.csv -O data/Wine.csv

--2023-10-27 11:43:01--  https://bilkav.com/Wine.csv
Resolving bilkav.com (bilkav.com)... 179.61.189.21
Connecting to bilkav.com (bilkav.com)|179.61.189.21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘data/Wine.csv’

data/Wine.csv           [ <=>                ]  11.20K  --.-KB/s    in 0.05s   

2023-10-27 11:43:05 (235 KB/s) - ‘data/Wine.csv’ saved [11464]



In [92]:
!ls data/

Ads_CTR_Optimisation.csv  maaslar_yeni.csv	  sepet.csv
Churn_Modelling.csv	  musteriler.csv	  veriler.csv
maaslar.csv		  Restaurant_Reviews.csv  Wine.csv
